Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

AllCops:
  Exclude:
    - 'bin/bundle'
    - 'lib/tasks/test.rake'
    - 'db/schema.rb'
    - 'db/migrate/00000002_add_service_name_to_active_storage_blobs.active_storage.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/factories/*'
    - 'db/migrate/*'
    - 'spec/models/*/*'
    - 'config/routes.rb'
    - 'spec/requests/*'
    - 'spec/requests/*/*'
    - 'config/environments/development.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'
