Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

AllCops:
  Exclude:
    - 'bin/bundle'
    - 'lib/tasks/test.rake'
    - 'db/schema.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/models/*/*'
    - 'spec/requests/*'
    - 'spec/requests/*/*'
    - 'config/environments/development.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
