Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

AllCops:
  Exclude:
    - 'bin/bundle'
    - 'lib/tasks/test.rake'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'
